name: mutation-test
run-name: ${{ github.actor }} is runing mutation tests
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  mutation-test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git configuration
        run: |
          git config --global user.name "jameswiseman76"
          git config --global user.email "james.wiseman@gmail.com"
          # Add any other custom Git configurations you need     
      - uses: actions/checkout@v4
      - uses: stryker-mutator/github-action@v0.0.2
        with:
          testProject: "src/MutationTestDemos.UnitTests/" # required
          breakAt: "75" # Optional
      - uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: ${{github.workspace}}/src/MutationTestDemos.UnitTests/StrykerOutput/**/**/*.html
