on:
  # Run the mutation tests when changes are pushed to the main branch
  push:
    branches:
      - 'main'
jobs:
  mutation-test:
    uses: actions/checkout@v3

    uses: stryker-mutator/github-action@v0.0.1
      with:
        testProject: "BusinessLogic.Test/" # required
        breakAt: "75" # Optional

    uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: ${{github.workspace}}/src/MutationTestDemos.UnitTests/StrykerOutput/**/**/*.html
